In [1]:
import pandas as pd 
import os

In [2]:
pwd = os.getcwd()

In [3]:
series_test = list(range(1,100))
pd.Series(series_test)

0      1
1      2
2      3
3      4
4      5
      ..
94    95
95    96
96    97
97    98
98    99
Length: 99, dtype: int64

In [4]:
filepath = pwd + "/simple_csv.csv"
#filepath

In [5]:
first_import = pd.read_csv(filepath, nrows=10)
first_import

    Column1   Column2   Column3
0  0.280925  0.910368  0.692982
1  0.719882  0.210024  0.761276
2  0.235752  0.059796  0.154667
3  0.603366  0.485614  0.013345
4  0.039985  0.236359  0.811832
5  0.015478  0.543641  0.112719
6  0.192540  0.409874  0.875082
7  0.380921  0.045468  0.515859
8  0.592471  0.786421  0.047249
9  0.072112  0.695694  0.409573

In [6]:
first_import["Column1"]

0    0.280925
1    0.719882
2    0.235752
3    0.603366
4    0.039985
5    0.015478
6    0.192540
7    0.380921
8    0.592471
9    0.072112
Name: Column1, dtype: float64

In [7]:
first_import["New Column"] = 12
first_import["New Column2"] = list(range(10))
first_import["Added Value"] = first_import["New Column"] + first_import["New Column2"]
first_import

    Column1   Column2   Column3  New Column  New Column2  Added Value
0  0.280925  0.910368  0.692982          12            0           12
1  0.719882  0.210024  0.761276          12            1           13
2  0.235752  0.059796  0.154667          12            2           14
3  0.603366  0.485614  0.013345          12            3           15
4  0.039985  0.236359  0.811832          12            4           16
5  0.015478  0.543641  0.112719          12            5           17
6  0.192540  0.409874  0.875082          12            6           18
7  0.380921  0.045468  0.515859          12            7           19
8  0.592471  0.786421  0.047249          12            8           20
9  0.072112  0.695694  0.409573          12            9           21

In [8]:
#first_import = first_import.drop(columns="New Column")
first_import.drop(columns="New Column2", inplace=True)
first_import

    Column1   Column2   Column3  New Column  Added Value
0  0.280925  0.910368  0.692982          12           12
1  0.719882  0.210024  0.761276          12           13
2  0.235752  0.059796  0.154667          12           14
3  0.603366  0.485614  0.013345          12           15
4  0.039985  0.236359  0.811832          12           16
5  0.015478  0.543641  0.112719          12           17
6  0.192540  0.409874  0.875082          12           18
7  0.380921  0.045468  0.515859          12           19
8  0.592471  0.786421  0.047249          12           20
9  0.072112  0.695694  0.409573          12           21

In [9]:
first_import.loc[:5, ["Column1", "Column2", "Column3", "Added Value", "New Column"]]

    Column1   Column2   Column3  Added Value  New Column
0  0.280925  0.910368  0.692982           12          12
1  0.719882  0.210024  0.761276           13          12
2  0.235752  0.059796  0.154667           14          12
3  0.603366  0.485614  0.013345           15          12
4  0.039985  0.236359  0.811832           16          12
5  0.015478  0.543641  0.112719           17          12

In [10]:
first_import.iloc[:6, :]

    Column1   Column2   Column3  New Column  Added Value
0  0.280925  0.910368  0.692982          12           12
1  0.719882  0.210024  0.761276          12           13
2  0.235752  0.059796  0.154667          12           14
3  0.603366  0.485614  0.013345          12           15
4  0.039985  0.236359  0.811832          12           16
5  0.015478  0.543641  0.112719          12           17

In [11]:
netflix = pd.read_csv(pwd + "/netflix_titles.csv")
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [12]:
list(netflix.columns)

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'rating',
 'duration',
 'listed_in',
 'description']

In [13]:
netflix.describe()

       release_year
count   7787.000000
mean    2013.932580
std        8.757395
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2018.000000
max     2021.000000

In [14]:
netflix["type"].unique()

array(['TV Show', 'Movie'], dtype=object)

In [15]:
netflix[netflix["country"] == "Singapore"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
333,s334,TV Show,Against the Tide,NaN,"Christopher Lee, Rui En, Desmond Tan, Zheng Ge...",Singapore,"July 1, 2017",2014,TV-14,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A detective and a psychologist investigating a...
511,s512,Movie,André & his olive tree,Josiah Ng,André Chiang,Singapore,"December 8, 2020",2020,TV-PG,104 min,"Documentaries, International Movies","As he prepares to close his restaurant, Michel..."
1064,s1065,TV Show,Bountiful Blessings,NaN,"Jessica Hsuan, Tay Ping Hui, Thomas Ong, Jeffr...",Singapore,"August 1, 2017",2011,TV-14,1 Season,"International TV Shows, TV Dramas, TV Sci-Fi &...",A former mortal who is now the Kitchen God coo...
2093,s2094,Movie,Fakkah Fuzz: Almost Banned,Michael McKay,Fakkah Fuzz,Singapore,"January 26, 2018",2018,TV-MA,61 min,Stand-Up Comedy,Stand-up comic Fakkah Fuzz mines cross-cultura...
2956,s2957,Movie,Imperfect,Steve Cheng,"Edwin Goh, Ian Fang Weijie, Phua Yida, Kimberl...",Singapore,"December 20, 2018",2012,TV-MA,95 min,"Action & Adventure, International Movies","After a brawl lands him in a Boys’ Home, a tee..."
3528,s3529,Movie,Lang Tong,Sam Loh,"William Lawandi, Angeline Yap, Vivienne Tseng,...",Singapore,"December 20, 2018",2015,TV-MA,82 min,"International Movies, Thrillers","After seducing a philandering con man, a rebel..."
4106,s4107,TV Show,Mind Game,NaN,"Tay Ping Hui, Joanne Peh, Zhang Yaodong, Paige...",Singapore,"June 1, 2017",2015,TV-14,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","With the help of a cop, a psychologist and a w..."
4138,s4139,Movie,Miss J Contemplates Her Choice,Jason Lai,"Kit Chan, Xiang Yun, Bobby Tonelli, Shane Pow,...",Singapore,"December 20, 2018",2014,TV-MA,89 min,"Dramas, International Movies, Thrillers",The life of a radio talk-show host is turned u...
4375,s4376,TV Show,Mystic Whispers,NaN,"Romeo Tan, Sheila Sim, Yuan Shuai, Aloysius Pang",Singapore,"July 1, 2017",2014,TV-14,1 Season,"International TV Shows, TV Dramas, TV Horror",After a car accident enables a young woman to ...
5870,s5871,TV Show,Sudden,NaN,"Rui En, Romeo Tan, Rebecca Lim, Zhang Zhenhuan",Singapore,"October 1, 2017",2013,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A car accident sends four lawyers spiraling in...
6087,s6088,TV Show,The Apartment,NaN,"Jamie Durie, Laurence Llewelyn-Bowen",Singapore,"December 14, 2018",2014,TV-PG,2 Seasons,"International TV Shows, Reality TV","With their eyes on the grand prize, amateur de..."
6311,s6312,TV Show,The Dream Catchers,NaN,"Rui En, Tay Ping Hui, Jesseca Liu, Shaun Chen,...",Singapore,"October 1, 2017",2009,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Four engineers from different walks of life cr...
6312,s6313,TV Show,The Dream Job,NaN,"Hugo Ng, Shaun Chen, Jeanette Aw, Rebecca Lim,...",Singapore,"June 1, 2017",2016,TV-14,1 Season,"International TV Shows, TV Dramas","A mysterious, wealthy man offers three people ..."
6481,s6482,TV Show,The In-Laws,NaN,"Louise Lee, Rui En, Pierre Png, Darren Lim, Cy...",Singapore,"August 1, 2017",2011,TV-14,1 Season,"International TV Shows, TV Dramas",She swore not to meddle in her kids' lives lik...
6716,s6717,TV Show,The Oath,NaN,"Christopher Lee, Jesseca Liu, Ann Kok, Kate Pa...",Singapore,"July 1, 2017",2011,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Two doctors with opposite approaches to treati...
6949,s6950,TV Show,The Truth Seekers,NaN,"Chen Hanwei, Rebecca Lim, Desmond Tan, Yusuke ...",Singapore,"July 1, 2017",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A veteran cop forms an agency dedicated to sol...
6957,s6958,TV Show,The Ultimatum,NaN,"Zoe Tay, Fann Wong, Li Nanxing, Tay Ping Hui, ...",Singapore,"July 1, 2017",2009,TV-14,1 Season,"International TV Shows, TV Dramas",Love and intrigue swirl around two women – one...
7128,s7129,TV Show,Together,NaN,"Jeanette Aw, Dai Xiangyu, Elvin Ng, Eelyn Kok,...",Singapore,"November 1, 2017",2009,TV-14,1 Season,"International TV Shows, TV Dramas","Spanning 30 years, a group of dedicated and di..."
7358,s7359,TV Show,Unriddle,NaN,"Rui En, Chen Liping, Tay Ping Hui, Andie Chen,...",Singapore,"July 1, 2017",2012,TV-14,2 Seasons,"Crime TV Shows, International TV Shows, TV Dramas",When a hard-nosed detective reluctantly partne...
7664,s7665,TV Show,World at Your Feet,NaN,"Ha Yu, Tay Ping Hui, Jeanette Aw, Elvin Ng, Yv...",Singapore,"July 1, 2017",2014,TV-14,1 Season,"International TV Shows, TV Dramas",A group of struggling individuals are united b...
7709,s7710,TV Show,Yes We Can!,NaN,"Romeo Tan, Rebecca Lim, Sora Ma, Xu Bin, Chen ...",Singapore,"July 1, 2017",2014,TV-14,1 Season,"International TV Shows, TV Dramas",When a frustrated businessman starts his own f...
7743,s7744,TV Show,Yours Fatefully,NaN,"Kingone Wang, Jesseca Liu, Xiang Yun, Chen Shu...",Singapore,"July 1, 2017",2012,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Two lonely singles meet on a blind date and sl...

In [16]:
netflix[(netflix["country"] == "Singapore") & (netflix["rating"] == "TV-MA")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2093,s2094,Movie,Fakkah Fuzz: Almost Banned,Michael McKay,Fakkah Fuzz,Singapore,"January 26, 2018",2018,TV-MA,61 min,Stand-Up Comedy,Stand-up comic Fakkah Fuzz mines cross-cultura...
2956,s2957,Movie,Imperfect,Steve Cheng,"Edwin Goh, Ian Fang Weijie, Phua Yida, Kimberl...",Singapore,"December 20, 2018",2012,TV-MA,95 min,"Action & Adventure, International Movies","After a brawl lands him in a Boys’ Home, a tee..."
3528,s3529,Movie,Lang Tong,Sam Loh,"William Lawandi, Angeline Yap, Vivienne Tseng,...",Singapore,"December 20, 2018",2015,TV-MA,82 min,"International Movies, Thrillers","After seducing a philandering con man, a rebel..."
4138,s4139,Movie,Miss J Contemplates Her Choice,Jason Lai,"Kit Chan, Xiang Yun, Bobby Tonelli, Shane Pow,...",Singapore,"December 20, 2018",2014,TV-MA,89 min,"Dramas, International Movies, Thrillers",The life of a radio talk-show host is turned u...
6949,s6950,TV Show,The Truth Seekers,NaN,"Chen Hanwei, Rebecca Lim, Desmond Tan, Yusuke ...",Singapore,"July 1, 2017",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A veteran cop forms an agency dedicated to sol...

In [17]:
netflix['computer_date'] = pd.to_datetime(netflix['date_added'], infer_datetime_format=True, errors='coerce')
netflix

/var/folders/f4/4bg21js179zf5ckjbm473g980000gn/T/ipykernel_7626/648979543.py:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  netflix['computer_date'] = pd.to_datetime(netflix['date_added'], infer_datetime_format=True, errors='coerce')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01

In [18]:
from datetime import datetime as dt

In [19]:
netflix["computer_date"].fillna(dt(2020, 1, 1), inplace=True)
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01

In [20]:
netflix["unix_time"] = netflix["computer_date"].astype(int)

In [21]:
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date,unix_time
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14,1597363200000000000
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23,1482451200000000000
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20,1545264000000000000
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16,1510790400000000000
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01,1577836800000000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19,1603065600000000000
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02,1551484800000000000
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25,1600992000000000000
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31,1604102400000000000
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01,1583020800000000000

In [22]:
netflix[["Date Part 1", "Date Part 2"]] = netflix["date_added"].str.split(", ", expand=True)
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date,unix_time,Date Part 1,Date Part 2
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14,1597363200000000000,August 14,2020
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23,1482451200000000000,December 23,2016
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20,1545264000000000000,December 20,2018
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16,1510790400000000000,November 16,2017
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01,1577836800000000000,January 1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19,1603065600000000000,October 19,2020
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02,1551484800000000000,March 2,2019
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25,1600992000000000000,September 25,2020
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31,1604102400000000000,October 31,2020
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01,1583020800000000000,March 1,2020

In [23]:
netflix.rename(columns={"Date Part 2": "Year"}, inplace=True)

In [24]:
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date,unix_time,Date Part 1,Year
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14,1597363200000000000,August 14,2020
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23,1482451200000000000,December 23,2016
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20,1545264000000000000,December 20,2018
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16,1510790400000000000,November 16,2017
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01,1577836800000000000,January 1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19,1603065600000000000,October 19,2020
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02,1551484800000000000,March 2,2019
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25,1600992000000000000,September 25,2020
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31,1604102400000000000,October 31,2020
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01,1583020800000000000,March 1,2020

In [25]:
netflix["cast"].fillna(value="no cast", inplace=True)
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date,unix_time,Date Part 1,Year
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14,1597363200000000000,August 14,2020
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23,1482451200000000000,December 23,2016
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20,1545264000000000000,December 20,2018
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16,1510790400000000000,November 16,2017
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01,1577836800000000000,January 1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19,1603065600000000000,October 19,2020
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02,1551484800000000000,March 2,2019
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25,1600992000000000000,September 25,2020
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31,1604102400000000000,October 31,2020
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,no cast,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01,1583020800000000000,March 1,2020

In [26]:
netflix["genre_count"] = netflix["listed_in"].map(lambda x: len(x.split(",")))
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date,unix_time,Date Part 1,Year,genre_count
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14,1597363200000000000,August 14,2020,3
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23,1482451200000000000,December 23,2016,2
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20,1545264000000000000,December 20,2018,2
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16,1510790400000000000,November 16,2017,3
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01,1577836800000000000,January 1,2020,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19,1603065600000000000,October 19,2020,2
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02,1551484800000000000,March 2,2019,3
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25,1600992000000000000,September 25,2020,3
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31,1604102400000000000,October 31,2020,2
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,no cast,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01,1583020800000000000,March 1,2020,2

In [27]:
netflix_movies_by_counrties = netflix.groupby("country")["show_id"].count().reset_index()
netflix_movies_by_counrties.sort_values(by="show_id", ascending=False)

                               country  show_id
549                      United States     2555
229                              India      923
462                     United Kingdom      397
291                              Japan      226
394                        South Korea      183
..                                 ...      ...
252  Indonesia, South Korea, Singapore        1
253          Indonesia, United Kingdom        1
254           Indonesia, United States        1
255                       Iran, France        1
680                           Zimbabwe        1

[681 rows x 2 columns]